rvm: 2.0.0
env:
- PUPPET_VERSION=2.7.25
- PUPPET_VERSION=3.0.2
- PUPPET_VERSION=3.1.1
- PUPPET_VERSION=3.2.4
- PUPPET_VERSION=3.3.2
- PUPPET_VERSION=3.4.3
- PUPPET_VERSION=3.5.1
- PUPPET_VERSION=3.6.2
- PUPPET_VERSION=3.7.5
notifications:
  email: false
  hipchat:
    rooms:
      secure: FP4SrP6H1os1T7JYdsXDuAe/A2B8saJ7eQLH+9j95h24tRt5GeXIpBT2YHHmqdSj9PjjrnlXw/a9iH5K6P3v55akN5fFuFQehSh85lPTc4/M+V4cg1s37Do4PBs0Rz9GJQl0eEEmYITB4GM3QjIVq1lXNNbMbZcV4nK1ARSUOl/Iqg1geM1lKwDZyP8OEoSlcm7d+n0NrOb7+flRMElDvQgGQUr0g6m7nF4XC6RC5JS+FQ3PScBEt7py62h2YeAZmt0nPFUXCZiE2p9PFzkHPMyccxmGkyrmMax7hTAXJPDoM3Is/xyAtMaIbcII9QE+fKVvUibUMcmdUntgb709kKQDAFpNJuyC2jbxKq4e1BMe22oW21X5LAZsKH/b2ZWJVp24u5CnEHmEPcYeWrIIeeV2xuImyvzQPaVbe1T+4AhtBWOXEBD6UIbaEs9alzJ+ZLJUK1Y//k+1FwJOC+JG2aS/9y5wqWp1wJYCLDO+fJSFifOWrb8lxKUZlhNDyAfsysw6FWMP46rr0kZUoPtc1IWG3ayeMr/itWsDPIP75X6GclC2jIyS/Xe0lzsXHv9Ud+yIKFfTs3Gg3gE2/7uFxirDfHij5MOQHqIeRgW/qDZd8g/1veoQ08QQAdR3BLPd9kUc9C2h8ycR9A1+4cHf+Uv7DKRAJmxNY7rMH2BqBBc=
    template:
    - 'Puppet Module - %{repository} #%{build_number} (%{build_url}) by %{author}:
      %{message}'
branches:
  only:
  - master
